services:
  # ---------------- PROD (DOCKER HUB) ----------------
  client-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: graphoraailabs/trackway-frontend:prod
    container_name: trackwayweb
    ports:
      - "4175:4175"
    restart: unless-stopped
