/**
 * ImportFromFlowModal lists the current user's Flow-generated projects and
 * imports the selected one into local storage.
 */
import { useEffect, useState } from 'react';
import { listRemoteProjects, fetchRemoteProject, type RemoteProjectSummary } from '@/services/FlowProjectsClient';

interface ImportFromFlowModalProps {
	open: boolean;
	onCancel?: () => void;
	onImport: (name: string, files: Record<string, string>) => Promise<void>;
}

const ImportFromFlowModal = ({ open, onCancel, onImport }: ImportFromFlowModalProps) => {
	const [projects, setProjects] = useState<RemoteProjectSummary[]>([]);
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const [importingId, setImportingId] = useState<string | null>(null);

	useEffect(() => {
		if (!open) return;
		setError(null);
		setLoading(true);
		listRemoteProjects()
			.then(setProjects)
			.catch((err) => {
				const message = err instanceof Error ? err.message : 'Failed to load Flow projects.';
				setError(message);
			})
			.finally(() => setLoading(false));
	}, [open]);

	if (!open) {
		return null;
	}

	const handleImport = async (project: RemoteProjectSummary) => {
		setError(null);
		setImportingId(project.id);
		try {
			const remote = await fetchRemoteProject(project.id);
			await onImport(remote.name, remote.files);
		} catch (err) {
			const message = err instanceof Error ? err.message : 'Failed to import project.';
			setError(message);
		} finally {
			setImportingId(null);
		}
	};

	return (
		<div
			className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm"
			role="dialog"
			aria-modal="true"
			aria-labelledby="import-from-flow-title"
		>
			<div className="w-full max-w-md rounded-xl border border-slate-200 bg-white p-6 shadow-xl">
				<div className="mb-4">
					<h2 id="import-from-flow-title" className="text-lg font-semibold text-slate-900">
						Import from Flow
					</h2>
					<p className="text-sm text-slate-500">
						Choose a board generated by the Flow agent to bring into Trackway.
					</p>
				</div>

				{loading ? (
					<p className="text-sm text-slate-500">Loading projects...</p>
				) : error ? (
					<p className="text-sm text-red-500">{error}</p>
				) : projects.length === 0 ? (
					<p className="text-sm text-slate-500">No Flow projects found for your account.</p>
				) : (
					<ul className="flex max-h-64 flex-col gap-2 overflow-y-auto">
						{projects.map((project) => (
							<li
								key={project.id}
								className="flex items-center justify-between rounded-md border border-slate-200 px-3 py-2"
							>
								<div>
									<p className="text-sm font-medium text-slate-900">{project.name}</p>
									<p className="text-xs text-slate-500">
										{new Date(project.updatedAt).toLocaleString()}
									</p>
								</div>
								<button
									type="button"
									onClick={() => handleImport(project)}
									disabled={importingId === project.id}
									className="rounded-md bg-sky-600 px-3 py-1.5 text-xs font-semibold text-white shadow-sm transition-colors duration-150 disabled:cursor-not-allowed disabled:bg-sky-300 hover:bg-sky-500"
								>
									{importingId === project.id ? 'Importing…' : 'Import'}
								</button>
							</li>
						))}
					</ul>
				)}

				<div className="mt-4 flex justify-end">
					<button
						type="button"
						onClick={onCancel}
						className="rounded-md border border-slate-300 px-4 py-2 text-sm font-medium text-slate-600 shadow-sm transition-colors duration-150 hover:border-slate-400 hover:text-slate-700"
					>
						Close
					</button>
				</div>
			</div>
		</div>
	);
};

export type { ImportFromFlowModalProps };
export default ImportFromFlowModal;
