name: Trackway Web CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build & Push Docker Image
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --cache-from type=registry,ref=graphoraailabs/trackway-frontend:cache \
            --cache-to type=registry,ref=graphoraailabs/trackway-frontend:cache,mode=max \
            -t graphoraailabs/trackway-frontend:prod \
            --push .

      # Deploy via SSH (KEY BASED)
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 60s
          command_timeout: 10m
          script: |
            cd /root/Trackway-full-application
            git fetch origin main
            git reset --hard origin/main
            docker ps -q --filter "publish=4173" | xargs -r docker rm -f || true
            docker ps -q --filter "publish=4175" | xargs -r docker rm -f || true
            docker rm -f trackwayweb || true
            docker rm -f trackway-frontend-prod || true
            docker compose pull client-prod
            docker compose up -d client-prod
